export const environment = {
  production: true,
  baseURL: "https://api.yarsi.ac.id/core",
  baseLocalURL: "https://api.yarsi.ac.id/bridge/endpoint",
  baseURLReport: "/api/upload",
  appID: "yarsi",
  kodePmb: "ws_pmb",
  passPmb: "abcdef",
  kodeSmart: "ws_smart",
  passSmart: "aksesApi#67",
  secret_key: "kpm_yarsi_2022",
  baseUrlDoc: "https://api.yarsi.ac.id/",
  AP: 2,
  AS: 3,
  BP: 2,
  BS: 1,
  CP: 1,
  CS: 2,
};
